name: 'Build'

on: [push, pull_request]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Install'
        run: npm ci
      - name: 'Configure'
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: 'config.json'
          json: ${{ github.event_name != 'pull_request' && secrets.CONFIG || '{}' }}
      - name: 'Build'
        run: npm run build
