name: 'Publish'

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Install'
        run: npm ci
      - name: 'Configure'
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: 'config.json'
          json: ${{ secrets.CONFIG }}
      - name: 'Publish'
        run: npm run publish
