name: 'Test'

on: [push, pull_request]

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Node'
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: 'Install'
        run: npm ci
      - name: 'Test'
        run: npm run test
